### ISSUE TITLE
No Queue

### ISSUE THREAD

**Issue by Bovive** [Drewster727/sabnzbd-influxdb-export#1]
First off, great script. Thanks for making it! For some reason I am pulling the Server Stats data but not the Queue data. Any idea why that might be? Thanks!

**Comment by Drewster727** [comment]
@Bovive sorry for the late reply

hmm I might need some more info. Do you see the new database being created in influxdb? Is the script running? etc.. What versions of everything are you using?

**Comment by Bovive** [comment]
No problem. Here are my versions:
Influx: 1.3.2
Your latest script (acquired it from here)

In Influx I have my database looks like this:
name: server_stats
fieldKey    fieldType
--------    ---------
total       integer
total_day   integer
total_month integer
total_week  integer

I only see server_stats, no queue data. Thanks again for your help!

**Comment by Drewster727** [comment]
More questions:
- What version of python?
- What version of sabnzbd?
- Have you tried running the script directly from the command line to see if it spits out any errors?

**Comment by Bovive** [comment]
Sabnzbd version 2.20
Python version 2.7.12

If I run it directly it just keeps returning 'kbpersec' over and over. Does that sound appropriate?

**Comment by Drewster727** [comment]
hi @Bovive I believe this is now fixed. Can you try it out?
It was a change they made to the sabnzbd api.

**Comment by Bovive** [comment]
It appears to be working now. Thanks for doing this!
